// NOTE: ALERT ERROR & SUCCESS
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// NOTE: REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

// NOTE: USER LOGGEDIN
export const USER_LOADED = 'USER_LOADED'

// NOTE: USER GUEST
export const AUTH_ERROR = 'AUTH_ERROR'

// NOTE: LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

// NOTE: LOGOUT
export const LOGOUT = 'LOGOUT'

// NOTE: ENGINEER
export const GET_ENGINEERS = 'GET_ENGINEERS'
export const GET_ENGINEER = 'GET_ENGINEER'
export const ADD_ENGINEER = 'ADD_ENGINEER'
export const UPDATE_ENGINEER = 'UPDATE_ENGINEER'
export const ENGINEER_ERROR = 'ENGINEER_ERROR'
export const DELETE_ENGINEER = 'DELETE_ENGINEER'

// NOTE: COMPANY
export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_COMPANY = 'GET_COMPANY'
export const ADD_COMPANY = 'ADD_COMPANY'
export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const COMPANY_ERROR = 'COMPANY_ERROR'
export const DELETE_COMPANY = 'DELETE_COMPANY'
