// NOTE: ALERT ERROR & SUCCESS
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// NOTE: REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
// NOTE: USER LOGGEDIN
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
// NOTE: LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
// NOTE: LOGOUT
export const LOGOUT = 'LOGOUT'
// NOTE: ENGINEER
export const GET_ENGINEERS = 'GET_ENGINEERS'
export const GET_ENGINEERS_ERROR = 'GET_ENGINEERS_ERROR'
export const GET_CURRENT_PROFILE_ENGINEER = 'GET_CURRENT_PROFILE_ENGINEER'
export const GET_CURRENT_PROFILE_ENGINEER_ERROR = 'GET_CURRENT_PROFILE_ENGINEER_ERROR'
export const UPDATE_PROFILE_ENGINEER = 'UPDATE_PROFILE_ENGINEER'
export const UPDATE_PROFILE_ENGINEER_ERROR = 'UPDATE_PROFILE_ENGINEER_ERROR'
export const DELETE_ENGINEER = 'DELETE_ENGINEER'
export const DELETE_ENGINEER_ERROR = 'DELETE_ENGINEER_ERROR'
// NOTE: COMPANY
export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_COMPANIES_ERROR = 'GET_COMPANIES_ERROR'
export const GET_CURRENT_PROFILE_COMPANY = 'GET_CURRENT_PROFILE_COMPANY'
export const GET_CURRENT_PROFILE_COMPANY_ERROR = 'GET_CURRENT_PROFILE_COMPANY_ERROR'
export const UPDATE_PROFILE_COMPANY = 'UPDATE_PROFILE_COMPANY'
export const UPDATE_PROFILE_COMPANY_ERROR = 'UPDATE_PROFILE_COMPANY_ERROR'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const DELETE_COMPANY_ERROR = 'DELETE_COMPANY_ERROR'
// NOTE: DELETE ACCOUNT
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
